apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hallen

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

images:
  - name: flashcards-backend
    newName: ghcr.io/kaese72/flash-cards-backend
    newTag: v0.0.2
  - name: flashcards-frontend
    newName: ghcr.io/kaese72/flash-cards-frontend
    newTag: v0.0.2
